### ISSUE TITLE
UnityToolbox 脚本丢失

### ISSUE THREAD

**Issue by Personuo** [EricHaung/BilibiliURLPhraserForUnity#1]
你好，我下完后，放到项目里去就报错了
如果有时间的话，麻烦修复一下，谢谢！

**Comment by EricHaung** [comment]
稍等我這兩天修改喔

**Comment by EricHaung** [comment]
已修正
順帶一提，之前只是隨手放上腳本，現在正式上傳整個專案並做些微修改
如果有其他地方有問題歡迎再提問，隨手上傳的專案被其他人看到並使用其實還滿開心的

**Comment by Personuo** [comment]
这个是能直接读出url然后给unity解析再video上播放吗?能不能下载视频?

**Comment by EricHaung** [comment]
目前沒有寫這樣的機制，再給我兩天我改一下
Bilibili在比較高的畫質下會把音軌和視訊畫面切開，所以需要做合併
